# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Build Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build / Android (preview)
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build / iOS (preview)
    type: build
    params:
      platform: ios
      profile: preview
