# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    name: Type-check
    type: custom
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Type-check
        run: bunx tsc --noEmit
